#data_source:
#  type: upload_file
#  info_list:
#    data_source_type: upload_file
#    file_info_list:
#      file_ids:
#        - 17d74bd8-2a34-4065-a56d-e2b30497cda3
indexing_technique: high_quality
process_rule:
  rules:
    pre_processing_rules:
      - id: remove_extra_spaces
        enabled: true
      - id: remove_urls_emails
        enabled: false
    segmentation:
      separator: "&&&&&"
      max_tokens: 512
      chunk_overlap: 50
  mode: custom
doc_form: text_model
doc_language: Chinese Simplified
retrieval_model:
  search_method: hybrid_search
  reranking_enable: true
  reranking_mode: weighted_score
  reranking_model:
    reranking_provider_name: langgenius/tongyi/tongyi
    reranking_model_name: gte-rerank-v2
  weights:
    weight_type: customized
    keyword_setting:
      keyword_weight: 0.3
    vector_setting:
      vector_weight: 0.7
      embedding_model_name: text-embedding-v3
      embedding_provider_name: langgenius/tongyi/tongyi
  top_k: 10
  score_threshold_enabled: false
  score_threshold: 0
embedding_model: text-embedding-v3
embedding_model_provider: langgenius/tongyi/tongyi
